export const GET_ALL_DOGS = "GET_ALL_DOGS";
export const GET_DOG_DETAILS_BY_ID = "GET_DOG_DETAILS_BY_ID";
export const GET_DOG_BY_NAME = "GET_DOG_BY_NAME";
export const GET_ALL_TEMPERAMENTS = "GET_ALL_TEMPERAMENTS";
export const POST_CREATED_DOG = "POST_CREATED_DOG"
export const FILTERS = "FILTERS";
export const GET_FILTER_TEMPERAMENTS ="GET_FILTER_TEMPERAMENTS"
export const LIMPIAR = "LIMPIAR"